[FIX] Remove ProGuard files from debug build to fix ClassNotFoundException
The debug build was still applying ProGuard files even with minifyEnabled=false,
causing ClassNotFoundException for MycelApplicationImpl at runtime.

Error was:
java.lang.ClassNotFoundException: Didn't find class "com.quantumresearch.mycel.app.android.MycelApplicationImpl"

Changes:
- Commented out proguardFiles for debug buildType
- Commented out testProguardFiles for debug buildType
- Release builds still use ProGuard (appropriate)

This should fix the immediate crash on app launch.